name: Tests

on: [push, pull_request]

env:
  TEST_RUN: 1

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
        working-directory: ./server

      - run: npm run test-ci
        working-directory: ./server
        env:
          CI: true
