name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
        working-directory: ./server

      - run: npm test
        working-directory: ./server
        env:
          CI: true

  ui-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
        node-version: [12.x, 14.x]
        browser: ["chrome"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          project: ./client